% AUTHOR:   Michael Cortez, mcortez@fsu.esu
% DATE:     February 2023
% PURPOSE:  Illustrate dependence of infection prevalence on parameter values
% INPUTS:   txt files of eq values and parameters generated by Maple
% METHOD:   A: Simulate model for varying parameter values and plot
%           B: Import data from txt files and plot
% OUTPUTS:  Curves showing relationships between state variable and parameters

figure('Position',[10 10 1000 600]);

    newcolors = [0 0 255
             60 0 190
             130 0 130
             190 0 60
             255 0 0 ]/255;
    colororder(newcolors)
    
    

%% Panel A: Sensitivity to mC
% Model parameter values
    rS = 6;
    rC = 6;
    rI = 3;
    rD = 3;
    K = 1000;
    mS = 2;
    mI = 10;
    mD = 10;
    betaS = 2; 
    betaC = 2; 
    chiI = 6;
    chiD = [1 3 5 7 9];
    u = 1;
    delta = 2;
    mC = [2 2.5 3 3.5 4 4.5 5 5.5 6 6.5 7 7.5 8];
    tf = 500;
    times = 0:.01:tf;
    
% Simulate model for each parameter combination
    Nvals = zeros(length(mC),length(chiD));
    Thetavals = zeros(length(mC),length(chiD));
    Itotalvals = zeros(length(mC),length(chiD));
    
    for ii=1:length(mC)
        for jj = 1:length(chiD)
            parms = [rS rC rI rD K mS mC(ii) mI mD betaS betaC chiI chiD(jj) u delta];
            x0 = [K,0,0,0,100]; % initial density values
            [t,x] = ode45(@model_NXYZP,times,x0,[],parms);
            Nvals(ii,jj) = x(end,1);
            Thetavals(ii,jj) = x(end,3);
            Itotalvals(ii,jj) = x(end,1)*x(end,3);
        end
    end
    
% Plot Equilibrium values    
     
    subplot(231) 
    hold on

    for jj = length(chiD):-1:1
        plot(mC,Thetavals(:,jj),'LineWidth',2,...
        'DisplayName',strcat('\chi_D=',num2str(chiD(jj)))) 
    end
    xlim([mC(1) mC(end)])
    xlabel('Compromised Mortality Rate (m_C)')
    ylabel('Infection Prevalence (\Theta^*)')
    title('A');
    legend('show','Location','northeast',...
    'FontSize', 10)
    set(legend,'NumColumns',1)
    set(gca,'Box','on')
    
%% Panel B: Sensitivity to rC
% Model parameter values
    rS = 7;
    rC = [2 3 4 5 6 7];
    rI = 4;
    rD = 4;
    K = 1000;
    mS = 2;
    mC =3;
    mI = 10;
    mD = 10;
    betaS = 2; 
    betaC = 2; 
    chiI = 6;
    chiD = [0 3 6 9 12];
    u = 1;
    delta = 2;
    tf = 750;
    times = 0:.01:tf;
    
% Simulate model for each parameter combination
    Nvals = zeros(length(rC),length(chiD));
    Thetavals = zeros(length(rC),length(chiD));
    Itotalvals = zeros(length(rC),length(chiD));
    
    for ii=1:length(rC)
        for jj = 1:length(chiD)
            parms = [rS rC(ii) rI rD K mS mC mI mD betaS betaC chiI chiD(jj) u delta];
            x0 = [K,0,0,0,100]; % initial density values
            [t,x] = ode45(@model_NXYZP,times,x0,[],parms);
            Nvals(ii,jj) = x(end,1);
            Thetavals(ii,jj) = x(end,3);
            Itotalvals(ii,jj) = x(end,1)*x(end,3);
        end
    end
    
% Plot Equilibrium values    
     
    subplot(232) 
    hold on

    for jj = 1:length(chiD)
        plot(rC,Thetavals(:,jj),'LineWidth',2,...
        'DisplayName',strcat('\chi_D=',num2str(chiD(jj))))
    end
    xlim([rC(1) rC(end)])
    xlabel('Compromised Reproduction Rate (r_C)')
    ylabel('Infection Prevalence (\Theta^*)','color','white')
    title('B');
    legend('show','Location','northeast',...
    'FontSize', 10)
    set(legend,'NumColumns',1)
    set(gca,'Box','on')    

%% Panel C: Sensitivity to betaC ) NEED MAPLE TO EXPORT EQ POINTS
% Model parameter values
    rS = 6;
    rC = [2 3 4 5 6];
    rI = 3;
    rD = 3;
    K = 1000;
    mS = 3;
    mC = 1;
    mI = 8;
    mD = 8;
    betaS = 3; 
    betaC = 0:1:9; 
    chiI = 10;
    chiD = 10;
    u = 1;
    delta = 1;
    tf = 2000;
    times = 0:.01:tf;
    
    Curve1 = importdata('NumericalEq/dThetadbetaC_rC1_Thetasave1.txt');
    Parmsave1 = importdata('NumericalEq/dThetadbetaC_rC1_Thetasave1_parm.txt');
    Curve2 = importdata('NumericalEq/dThetadbetaC_rC2_Thetasave1.txt');
    Parmsave2 = importdata('NumericalEq/dThetadbetaC_rC2_Thetasave1_parm.txt');
    Curve3 = importdata('NumericalEq/dThetadbetaC_rC3_Thetasave1.txt');
    Parmsave3 = importdata('NumericalEq/dThetadbetaC_rC3_Thetasave1_parm.txt');
    Curve4 = importdata('NumericalEq/dThetadbetaC_rC4_Thetasave1.txt');
    Parmsave4 = importdata('NumericalEq/dThetadbetaC_rC4_Thetasave1_parm.txt');
    Curve5 = importdata('NumericalEq/dThetadbetaC_rC5_Thetasave1.txt');
    Parmsave5 = importdata('NumericalEq/dThetadbetaC_rC5_Thetasave1_parm.txt');
    
    
    Curves = [Curve1 Curve2 Curve3 Curve4 Curve5];
    
% Plot Equilibrium values    
     
    subplot(233) 
    hold on

    for jj = 1:length(rC)
        plot(Parmsave1,Curves(:,jj),'LineWidth',2,...
        'DisplayName',strcat('r_C=',num2str(rC(jj)))) 
    end
    xlim([2.5 betaC(end)])
    xlabel('Compromised Infection Rate (\beta_C)')
    ylabel('Infection Prevalence (Theta^*)','color','white')
    title('C');
    legend('show','Location','northeast',...
    'FontSize', 10)
    set(legend,'NumColumns',1)
    set(gca,'Box','on')  


%% Panel D: Sensitivity to mD
% Model parameter values
    rS = 4;
    rC = 4;
    rI = 2;
    rD = 2;
    K = 100;
    mS = 1;
    mC =4;
    mI = 2;
    mD = 7:20;
    betaS = 4; 
    betaC = 4; 
    chiI = 3;
    chiD = [1 3 5 7 9];
    u = 1.5;
    delta = 1.5;
    tf = 500;
    times = 0:.01:tf;
    
% Simulate model for each parameter combination
    Nvals = zeros(length(mD),length(chiD));
    Thetavals = zeros(length(mD),length(chiD));
    Itotalvals = zeros(length(mD),length(chiD));
    
    for ii=length(mD):-1:1
        for jj = 1:length(chiD)
            parms = [rS rC rI rD K mS mC mI mD(ii) betaS betaC chiI chiD(jj) u delta];
            x0 = [K,0,0,0,100]; % initial density values
            [t,x] = ode45(@model_NXYZP,times,x0,[],parms);
            Nvals(ii,jj) = x(end,1);
            Thetavals(ii,jj) = x(end,3);
            Itotalvals(ii,jj) = x(end,1)*x(end,3);
        end
    end
    
% Plot Equilibrium values    
     
    subplot(234) 
    hold on

    for jj = 1:length(chiD)
        plot(mD,Thetavals(:,jj),'LineWidth',2,...
        'DisplayName',strcat('\chi_D=',num2str(chiD(jj))),...
        'color',[(158-3)/4/255*(jj-1)+3/255 (194-1)/4/255*(jj-1)+1/255 (255-140)/4/255*(jj-1)+140/255]) 
    end
    xlim([mD(1) mD(end)])
    xlabel('Decimated Mortality Rate (m_D)')
    ylabel('Infection Prevalence (\Theta^*)')
    title('D');
    legend('show','Location','northeast',...
    'FontSize', 10)
    set(legend,'NumColumns',1)
    set(gca,'Box','on')  

%% Panel E: Sensitivity to rD
% Model parameter values
    rS = 4;
    rC = 4;
    rI = 2;
    rD = 0:0.25:2;
    K = 100;
    mS = 1;
    mC =1;
    mI = 2;
    mD = 3;
    betaS = 4; 
    betaC = 2; 
    chiI = 10;
    chiD = [1 3 6 9 12];
    u = 2;
    delta = 4;
    tf = 500;
    times = 0:.01:tf;
    
% Simulate model for each parameter combination
    Nvals = zeros(length(rD),length(chiD));
    Thetavals = zeros(length(rD),length(chiD));
    Itotalvals = zeros(length(rD),length(chiD));
    
    for ii=1:length(rD)
        for jj = 1:length(chiD)
            parms = [rS rC rI rD(ii) K mS mC mI mD betaS betaC chiI chiD(jj) u delta];
            x0 = [K,0,0,0,100]; % initial density values
            [t,x] = ode45(@model_NXYZP,times,x0,[],parms);
            Nvals(ii,jj) = x(end,1);
            Thetavals(ii,jj) = x(end,3);
            Itotalvals(ii,jj) = x(end,1)*x(end,3);
        end
    end
    
% Plot Equilibrium values    
     
    subplot(235) 
    hold on

    for jj = length(chiD):-1:1
        plot(rD,Thetavals(:,jj),'LineWidth',2,...
        'DisplayName',strcat('\chi_D=',num2str(chiD(jj)))) 
    end
    xlim([rD(1) rD(end)])
    xlabel('Decimated Reproduction Rate (r_D)')
    ylabel('Infection Prevalence (\Theta^*)','color','white')
    title('E');
    legend('show','Location','northeast',...
    'FontSize', 10)
    set(legend,'NumColumns',1)
    set(gca,'Box','on')       

%% Panel F: Sensitivity to chiD - NEED MAPLE TO EXPORE EQ VALUES
% Model parameter values
    rS = [4 6 8 10 12];
    rC = 2;
    rI = 2;
    rD = 2;
    K = 100;
    mS = 1;
    mC =2;
    mI = 3;
    mD = 3;
    betaS = 4; 
    betaC = 4; 
    chiI = 3;
    chiD = [2 3 4 5 6 7];
    u = 3;
    delta = 3;
    tf = 500;
    times = 0:.01:tf;

    Curve1 = importdata('NumericalEq/dThetadchiD_rS4_Thetasave1.txt');
    Parmsave1 = importdata('NumericalEq/dThetadchiD_rS4_Thetasave1_parm.txt');
    Curve2 = importdata('NumericalEq/dThetadchiD_rS6_Thetasave1.txt');
    Parmsave2 = importdata('NumericalEq/dThetadchiD_rS6_Thetasave1_parm.txt');
    Curve3 = importdata('NumericalEq/dThetadchiD_rS8_Thetasave1.txt');
    Parmsave3 = importdata('NumericalEq/dThetadchiD_rS8_Thetasave1_parm.txt');
    Curve4 = importdata('NumericalEq/dThetadchiD_rS10_Thetasave1.txt');
    Parmsave4 = importdata('NumericalEq/dThetadchiD_rS10_Thetasave1_parm.txt');
    Curve5 = importdata('NumericalEq/dThetadchiD_rS12_Thetasave1.txt');
    Parmsave5 = importdata('NumericalEq/dThetadchiD_rS12_Thetasave1_parm.txt');
    
    Curves = [Curve1 Curve2 Curve3 Curve4 Curve5];
       
% Plot Equilibrium values    
     
    subplot(236) 
    hold on

    for jj = 1:length(rS)
        plot(Parmsave1,Curves(:,jj),'LineWidth',2,...
        'DisplayName',strcat('r_S=',num2str(rS(jj))),...
        'color',[(158-3)/4/255*(jj-1)+3/255 (194-1)/4/255*(jj-1)+1/255 (255-140)/4/255*(jj-1)+140/255]) 
    end
    xlim([3 Parmsave1(end)])
    xlabel('Decimated Shedding Rate (\chi_D)')
    ylabel('Infection Prevalence (\Theta^*)','color','white')
    title('F');
    legend('show','Location','northwest',...
    'FontSize', 10)
    set(legend,'NumColumns',1)
    set(gca,'Box','on')    
